version: '3'

services:
  crawler:
    build: ./
    volumes:
     - ./data:/data
    command:
      - "crawl"
      - "--timeout"
      - "10m"
      - "--crawler-db"
      - "/data/crawler-prod.db"
      - "--nodeURL"
      - "https://rpc-nebulas-mainnet.uniultra.xyz "
      - "--nodefile"
      - "/data/nodes.json"
      - "--networkid"
      - "0"
      - "--geoipdb"
      - "/data/GeoLite2-Country.mmdb"
      - "--addr"
      - ":43794"
      - "--genesisHash"
      - "0x54e033c612a9b1a8ac8c6cb131f513202648f19b3a2756f8e2e40877d280606c"

  api:
    build: ./
    volumes:
     - ./data:/data
    depends_on:
     - crawler
    command: "api --crawler-db /data/crawler-prod.db --api-db /data/api-prod.db"

  frontend:
    build: ./frontend
    volumes:
     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     - ./data:/data
    depends_on:
     - api
    ports:
     - 8080:8080
